<a href="https://colab.research.google.com/github/tanjiro-01/real_estate_cf/blob/main/real_estate_cf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Readme

In [ ]:
"""
Real Estate Underwriting Score Prediction System
Thejaswi Bhat H
CodeFrontier Software

Objective
Build a Machine Learning model to predict an underwriting score (0–100) and categorize risk levels for real estate investment decisions.


1. Problem Description
2. Import Libraries
3. Load Dataset
4. Data Quality Checks
5. Exploratory Data Analysis (EDA)
6. Data Cleaning

Builder Score (25%)
Property Score (35%)
Market Score (20%)
Financial Score (20%)

"""

'\nReal Estate Underwriting Score Prediction System\nThejaswi Bhat H \nCodeFrontier Software \n\nObjective\nBuild a Machine Learning model to predict an underwriting score (0–100) and categorize risk levels for real estate investment decisions.\n\n1. Problem Description\n2. Import Libraries\n3. Load Dataset\n4. Data Quality Checks\n5. Exploratory Data Analysis (EDA)\n6. Data Cleaning\n'

# Import Libraries

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load data

In [ ]:
file_path = "/content/data/data.xlsx"
df = pd.read_excel(file_path)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (500, 43)

,property_id,city,builder_name,builder_years_in_business,projects_completed,avg_delay_months,debt_to_equity_ratio,rera_violations,litigation_count,is_publicly_listed,...,payment_plan_type,builder_score,property_score,market_score,financial_score,underwriting_score,risk_category,expected_irr_pct,recommendation,confidence_level
0,VAD-2024-0001,Vadodara,Mahindra Lifespaces,18,40,4.4,0.50,0,0,1,...,CLP,92.5,67.5,54.0,40.0,70.5,Moderate Risk,3.2,INVEST,High
1,SUR-2024-0002,Surat,Local Builder 1,9,13,6.7,2.64,1,7,0,...,CLP,54.0,51.5,57.5,55.5,44.1,High Risk,2.9,AVOID,High
2,BAN-2024-0003,Bangalore,Piramal Realty,10,10,4.1,1.07,0,0,1,...,CLP,77.5,74.5,43.5,48.0,68.8,Moderate Risk,4.8,INVEST,Medium
3,IND-2024-0004,Indore,Jaypee Group,26,54,28.0,3.32,9,19,0,...,SUB,44.0,52.5,62.5,63.0,36.5,High Risk,14.7,AVOID,High
4,MUM-2024-0005,Mumbai,Prestige Group,30,93,1.3,1.30,0,0,1,...,CLP,86.5,57.5,71.0,76.0,74.2,Moderate Risk,15.6,INVEST,Medium

In [6]:
# null check
df.info()
df.isnull().sum().sort_values(ascending=False).head(20)
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   property_id                500 non-null    object
 1   city                       500 non-null    object
 2   builder_name               500 non-null    object
 3   builder_years_in_business  500 non-null    int64
 4   projects_completed         500 non-null    int64
 5   avg_delay_months           500 non-null    float64
 6   debt_to_equity_ratio       500 non-null    float64
 7   rera_violations            500 non-null    int64
 8   litigation_count           500 non-null    int64
 9   is_publicly_listed         500 non-null    int64
 10  net_worth_crores           500 non-null    int64
 11  city_tier                  500 non-null    int64
 12  distance_to_metro_km       500 non-null    float64
 13  distance_to_cbd_km         500 non-null    float64
 14  price_per_sqft             500 non-null    int64
 15  market_avg_price_sqft      500 non-null    int64
 16  construction_stage_pct     500 non-null    float64
 17  total_units                500 non-null    int64
 18  units_sold_pct             500 non-null    float64
 19  rera_registered            500 non-null    int64
 20  amenity_score              500 non-null    int64
 21  inventory_months           500 non-null    float64
 22  price_cagr_3yr             500 non-null    float64
 23  rental_yield_pct           500 non-null    float64
 24  monthly_absorption_pct     500 non-null    float64
 25  new_supply_units           500 non-null    int64
 26  infra_score                500 non-null    int64
 27  employment_growth_pct      500 non-null    float64
 28  investment_amount_lakhs    500 non-null    float64
 29  holding_period_months      500 non-null    int64
 30  loan_to_value_pct          500 non-null    float64
 31  interest_rate_pct          500 non-null    float64
 32  expected_rental_yield      500 non-null    float64
 33  payment_plan_type          500 non-null    object
 34  builder_score              500 non-null    float64
 35  property_score             500 non-null    float64
 36  market_score               500 non-null    float64
 37  financial_score            500 non-null    float64
 38  underwriting_score         500 non-null    float64
 39  risk_category              500 non-null    object
 40  expected_irr_pct           500 non-null    float64
 41  recommendation             500 non-null    object
 42  confidence_level           500 non-null    object
dtypes: float64(21), int64(15), object(7)
memory usage: 168.1+ KB

np.int64(0)

# Data Checks

In [8]:
df.columns
df.dtypes

property_id                   object
city                          object
builder_name                  object
builder_years_in_business      int64
projects_completed             int64
avg_delay_months             float64
debt_to_equity_ratio         float64
rera_violations                int64
litigation_count               int64
is_publicly_listed             int64
net_worth_crores               int64
city_tier                      int64
distance_to_metro_km         float64
distance_to_cbd_km           float64
price_per_sqft                 int64
market_avg_price_sqft          int64
construction_stage_pct       float64
total_units                    int64
units_sold_pct               float64
rera_registered                int64
amenity_score                  int64
inventory_months             float64
price_cagr_3yr               float64
rental_yield_pct             float64
monthly_absorption_pct       float64
new_supply_units               int64
infra_score                    int64
employment_growth_pct        float64
investment_amount_lakhs      float64
holding_period_months          int64
loan_to_value_pct            float64
interest_rate_pct            float64
expected_rental_yield        float64
payment_plan_type             object
builder_score                float64
property_score               float64
market_score                 float64
financial_score              float64
underwriting_score           float64
risk_category                 object
expected_irr_pct             float64
recommendation                object
confidence_level              object
dtype: object

In [12]:
#missing values
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

missing_percent = (df.isnull().sum()/len(df))*100
missing_report = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percent": missing_percent
}).sort_values(by="missing_count", ascending=False)

missing_report.head(15)

                           missing_count  missing_percent
property_id                            0              0.0
city                                   0              0.0
builder_name                           0              0.0
builder_years_in_business              0              0.0
projects_completed                     0              0.0
avg_delay_months                       0              0.0
debt_to_equity_ratio                   0              0.0
rera_violations                        0              0.0
litigation_count                       0              0.0
is_publicly_listed                     0              0.0
net_worth_crores                       0              0.0
city_tier                              0              0.0
distance_to_metro_km                   0              0.0
distance_to_cbd_km                     0              0.0
price_per_sqft                         0              0.0

In [13]:
#duplicate check
df.duplicated().sum()

np.int64(0)

In [14]:
df["underwriting_score"].describe()

count    500.000000
mean      65.652200
std        9.914653
min       29.600000
25%       61.675000
50%       67.050000
75%       72.000000
max       86.800000
Name: underwriting_score, dtype: float64

In [15]:
df["risk_category"].value_counts()

risk_category
Moderate Risk       303
Medium-High Risk    136
High Risk            41
Low Risk             15
Avoid                 5
Name: count, dtype: int64